Feat/161 mypage UI finish
team-MUMENT/MUMENT-AOS pull request #164
Opened 2023-01-18 13:49 UTC by jinsilWoo

## 🎸 작업한 내용
-  차단하기 알럿 구현 과 차단해제 버튼 누르고 아이템 삭제 되는 것을 구현하였습니다.
-  로그아웃 알럿 구현과 로그아웃을 누르면 LoginActivity 로 넘어갑니다.
-  마이페이지 백 버튼 이동하는 것도 구현하였습니다~
-  마이페이지 터치영역 고려하여 xml 수정하였습니다!

## 🎶 PR Point

- 차단해제 버튼 눌렀을 때에 아이템이 삭제 될 때 마지막 아이템이 반짝 거리는 건지 뭔지..어색한데 이유를 모르겠습니당~영상 참고바람*^^*
- 백버튼 눌렀을 때 구현을 하였는데 모든 백버튼에 같은 함수 내용이 적용되는데 더 좋은 방법이 있을까요 천재님들..
- 보관함에서 마이페이지 넘어가는 버튼 이벤트는 작업중인 혜빈이꺼와 충돌 날까봐 상의해서 혜빈이가 구현하기로 하였습니당~👍
- 공지사항 detail 로 넘어가는 부분은 activity에서 fragment 로 바꿀 예정인데,,아직 안한점...,,,,^-ㅠ
- 마이페이지 터치 영역은 일단 제 임의로 한거라..디자인한테 조만간 물어볼예정~제가 못찾는 걸지두..

## 📸 스크린샷

https://user-images.githubusercontent.com/97952129/213187661-ca6b6dc9-a72a-4170-959c-a66acc016ed6.mov

## 💽 관련 이슈
- Resolved: #161

2023-01-22 07:33 UTC, lhb8106 approved these changes
backstack 번거로웠을텐데 너무 고생하셨어용~! 진실언니 짱짱걸 ❣️

2023-01-22 07:33 UTC, lhb8106 commented on feature/mypage/src/main/java/com/mument_android/mypage/fragment/BlockUserManagementFragment.kt
> +                blockUserManagementAdapter.submitList(currentList)
몬가 깜빡거리는 이유가 DiffUtil 작동방식 자체가 단순하게 기존 아이템을 지우고, 갱신하는 식으로 동작하기 때문에 변경되면서 깜빡거리는 거이지 않을까.. 싶긴 합니다만.. 다른 고수님들 의견이 궁금하네여

2023-01-22 07:33 UTC, lhb8106 commented on feature/mypage/src/main/java/com/mument_android/mypage/fragment/NoticeFragment.kt
> +    }
backstack 관리 최고 !

2023-01-22 07:33 UTC, lhb8106 commented on feature/mypage/src/main/java/com/mument_android/mypage/fragment/UnregisterFragment.kt
> -//    }
이 코드는 필요 없어진 거 일까요 ?

2023-01-24 09:42 UTC, KkamSonLee requested changes
리뷰완!! 수정사항 반영해주세요~!!!

2023-01-24 09:42 UTC, KkamSonLee commented on core_dependent/src/main/java/com/mument_android/core_dependent/ui/MumentDialog.kt
> +            else -> ""
enum 타입으로 해도 좋을듯~!! 합니당

2023-01-24 09:42 UTC, KkamSonLee commented on feature/mypage/src/main/java/com/mument_android/mypage/MyPageActivity.kt
> +                    startActivity(intent)
- 이 방식이 더 좋을 것 같네요~!!
```suggestion
                    val intent = Intent(this, LogInActivity::class.java)
                    startActivity(intent)
                    finish()
```

2023-01-24 09:42 UTC, KkamSonLee commented on feature/mypage/src/main/java/com/mument_android/mypage/NoticeDetailActivity.kt
> +            onBackPressed()
이 친구 deprecated 되어서 OnBackPressedCallback이라는 친구 만들어서 넣어주는게 좋습니다~!!

2023-01-24 09:42 UTC, KkamSonLee commented on feature/mypage/src/main/java/com/mument_android/mypage/adapters/BlockUserManagementAdapter.kt
> +    private val userList: List<UserData>,
여기서 받지 말 것. 차단 해제 시에 해당 리스트에는 반영되지 않기에 userList[position] 받아올 때 문제가 생길듯

2023-01-24 09:42 UTC, KkamSonLee commented on feature/mypage/src/main/java/com/mument_android/mypage/adapters/BlockUserManagementAdapter.kt
>          holder.bind(getItem(position))
- 이 방식으로 바꿔주세용!!
```suggestion
        val userListPosition = getItem(position)
        holder.binding.btnUnblock.setOnClickListener {
            onClickDeleteUserItem.invoke(userListPosition)
        }
        holder.bind(userListPosition)
```

2023-01-24 09:42 UTC, KkamSonLee commented on feature/mypage/src/main/java/com/mument_android/mypage/fragment/BlockUserManagementFragment.kt
> +        )
뷰모델 사용해서 바인딩 해주세요~!!

2023-01-24 09:42 UTC, KkamSonLee commented on feature/mypage/src/main/java/com/mument_android/mypage/fragment/BlockUserManagementFragment.kt
> +                blockUserManagementAdapter.submitList(currentList)
해당 리스트는 뷰모델에 선언하고 delete 하는 로직도 뷰모델 통해서 처리해주시면 됩니다!!
fragment에서는 오직 LiveData만 observing 하여 리스트를 업데이트 시켜주시면 됩니다.
```kotlin

//activity
private fun observe() {
    blockViewModel.userList.observe(viewLifecycleOwner) { list ->
        blockUserManagementAdapter.submitList(list)
    }
}

//viewmodel
fun deleteUser(element: UserData) {
    val currentList = userList.value!!.toMutableList()
    currentList.remove(element)
    _userList.value = currentList
}
```

2023-01-24 09:42 UTC, KkamSonLee commented on feature/mypage/src/main/res/layout/fragment_block_user_management.xml
> +        android:layout_marginTop="20dp"
- 뷰모델로 처리하고 해당 코드 추가하면 깜빡임 없을 것입니당~!
```suggestion
        android:layout_height="0dp"
        android:layout_marginTop="20dp"
        app:layout_constraintBottom_toBottomOf="parent"
```

2023-01-25 13:10 UTC, jinsilWoo commented on core_dependent/src/main/java/com/mument_android/core_dependent/ui/MumentDialog.kt
> +            else -> ""
오홍 알겠습니다:)

2023-01-25 13:10 UTC, jinsilWoo commented on feature/mypage/src/main/java/com/mument_android/mypage/MyPageActivity.kt
> +                    startActivity(intent)
넵 수정하겠습니다!!

2023-01-25 13:10 UTC, jinsilWoo commented on feature/mypage/src/main/java/com/mument_android/mypage/NoticeDetailActivity.kt
> +            onBackPressed()
오호 감사합니당!

2023-01-25 13:10 UTC, jinsilWoo commented on feature/mypage/src/main/java/com/mument_android/mypage/adapters/BlockUserManagementAdapter.kt
> +    private val userList: List<UserData>,
넵넵! 수정해보겠습니다!

2023-01-25 13:11 UTC, jinsilWoo commented on feature/mypage/src/main/java/com/mument_android/mypage/adapters/BlockUserManagementAdapter.kt
>          holder.bind(getItem(position))
오홍! 감사합니다!! 👍

2023-01-25 13:11 UTC, jinsilWoo commented on feature/mypage/src/main/java/com/mument_android/mypage/fragment/BlockUserManagementFragment.kt
> +        )
넵 서버연결하면서 바꿔보겠습니다!

2023-01-25 13:12 UTC, jinsilWoo commented on feature/mypage/src/main/java/com/mument_android/mypage/fragment/BlockUserManagementFragment.kt
> +                blockUserManagementAdapter.submitList(currentList)
오 감사합니다! 변경해보겠습니다.!

2023-01-25 13:12 UTC, jinsilWoo commented on feature/mypage/src/main/res/layout/fragment_block_user_management.xml
> +        android:layout_marginTop="20dp"
bottom 에 제한을 안걸어줘서 그렇군요! 왕 배워갑니다! 감사해용~!~!

2023-01-25 15:04 UTC, KkamSonLee commented on feature/mypage/src/main/java/com/mument_android/mypage/MyPageActivity.kt
> +                    startActivity(intent)
Commit Suggestion 해주셔도 좋숩니당~!

2023-01-25 15:04 UTC, KkamSonLee commented on feature/mypage/src/main/java/com/mument_android/mypage/NoticeDetailActivity.kt
> +            onBackPressed()
근데 그냥 호출하는건 상관없겠네요 ! onBackPressed() 가 콜백으로 호출 될 때 뭔가 동작이 필요하다면 해당 기술 사용해주세요!!

2023-01-25 15:05 UTC, KkamSonLee commented on feature/mypage/src/main/java/com/mument_android/mypage/adapters/BlockUserManagementAdapter.kt
> +    private val userList: List<UserData>,
해당 코드 고쳐놓았긴 해봐서 혹시라도 안 되면 말해주세요!!

2023-01-27 06:04 UTC, jinsilWoo commented on feature/mypage/src/main/java/com/mument_android/mypage/NoticeDetailActivity.kt
> +            onBackPressed()
아하 그렇군요! 알겠숩니다:) 배워갑니당~!

2023-01-27 06:10 UTC, jinsilWoo commented on feature/mypage/src/main/java/com/mument_android/mypage/adapters/BlockUserManagementAdapter.kt
> +    private val userList: List<UserData>,
와아 감사합니다! 아주 잘됩니당ㅎㅎ

2023-01-29 11:53 UTC, KkamSonLee approved these changes

2023-01-29 12:21 UTC, merged