Feat/157 reflect locker modify
team-MUMENT/MUMENT-AOS pull request #165
Opened 2023-01-22 07:20 UTC by lhb8106

## 🎸 작업한 내용
- 보관함 수정사항 반영했습니다

## 🎶 PR Point

- 필터, grid/liner 선택, 좋아요&뮤멘트 여부 다 activityViewModel에 저장했습니다! 그리고 다른 탭 다녀오면 그냥 최상단으로 들어가게 했어유 !
- 토큰은 우선 개발을 편하게 하기 위해서.. 박아놨습니다! 문제가 된다면 말씀해주세용
- 보관함 수정된 api 적용시켰습니

## 📸 스크린샷

https://user-images.githubusercontent.com/69586104/213905112-57efda4f-882a-4e34-90ff-3efacc6e9739.mp4

## 💽 관련 이슈
- Resolved: #157

2023-01-24 09:51 UTC, KkamSonLee approved these changes
리뷰완~!!! 고생하셨습니다 !!

2023-01-24 09:51 UTC, KkamSonLee commented on app/src/main/java/com/mument_android/app/di/NetworkModule.kt
> +                )
나중에 수정

2023-01-24 09:51 UTC, KkamSonLee commented on data/src/main/java/com/mument_android/data/repository/LockerRepositoryImpl.kt
>      }.flowOn(Dispatchers.IO)
flowOn 지워주셔도 될 것 같습니당~~ retrofit2는 내부적으로 Dispatchers.IO를 사용합니다~!!

2023-01-24 09:51 UTC, KkamSonLee commented on feature/locker/src/main/java/com/mument_android/locker/LockerFragment.kt
> +    }
binding 변수에 직접 set 해주는 동작은 웬만하면 Fragment, Activity단에서는 없는게 좋긴합니다~!!

2023-01-24 09:51 UTC, KkamSonLee commented on feature/locker/src/main/java/com/mument_android/locker/viewmodels/LockerViewModel.kt
> +    var isMument : Boolean = true
접근 제한 붙여주면 좋을 것 같긴하네욜

2023-01-24 09:51 UTC, KkamSonLee commented on feature/locker/src/main/java/com/mument_android/locker/MyMumentFragment.kt
> +        }
데이터 바인딩으로 lockerViewModel.isGridLayout.value 값으로 Selected 조절 할 순 없을라나요..!

2023-01-24 09:51 UTC, KkamSonLee commented on feature/locker/src/main/java/com/mument_android/locker/MyMumentFragment.kt
>          lockerViewModel.myMuments.launchWhenCreated(viewLifecycleOwner.lifecycleScope){
launchWhenCreated 대신 collectFlowWhenStarted 사용해주세요!! 수집 제한을 걸어주셔야합니다 :)

2023-01-24 13:08 UTC, lhb8106 commented on feature/locker/src/main/java/com/mument_android/locker/LockerFragment.kt
> +    }
오홍 처음알았네용! 감사합니다

2023-01-24 13:08 UTC, lhb8106 commented on feature/locker/src/main/java/com/mument_android/locker/viewmodels/LockerViewModel.kt
> +    var isMument : Boolean = true
네넹!

2023-01-24 13:09 UTC, lhb8106 commented on feature/locker/src/main/java/com/mument_android/locker/MyMumentFragment.kt
> +        }
오호 뭔가 건드릴 경우의 수가 좀 있어서 박아넣긴했는데 시도해보겠슴니당!!

2023-01-24 13:09 UTC, lhb8106 commented on feature/locker/src/main/java/com/mument_android/locker/MyMumentFragment.kt
>          lockerViewModel.myMuments.launchWhenCreated(viewLifecycleOwner.lifecycleScope){
헉 네네 감사합니다! 반영하겠습니당 :)

2023-01-24 13:09 UTC, lhb8106 commented on app/src/main/java/com/mument_android/app/di/NetworkModule.kt
> +                )
넹 ~!

2023-01-24 13:10 UTC, lhb8106 commented on data/src/main/java/com/mument_android/data/repository/LockerRepositoryImpl.kt
>      }.flowOn(Dispatchers.IO)
오홍 감삼다 !!

2023-01-25 13:36 UTC, jinsilWoo approved these changes
변경사항 적용하시느라 고생많으셨습니다:) 딱히 리뷰남길게 없네용!! 이혜비니 최고👍

2023-01-25 13:36 UTC, jinsilWoo commented on feature/locker/src/main/java/com/mument_android/locker/LockerFragment.kt
> +    }
쿄쿄쿄 감사합니당  :)

2023-01-25 13:36 UTC, jinsilWoo commented on data/src/main/java/com/mument_android/data/repository/LockerRepositoryImpl.kt
>      }.flowOn(Dispatchers.IO)
오홍 배워갑니다~!

2023-01-25 15:03 UTC, KkamSonLee commented on feature/locker/src/main/java/com/mument_android/locker/MyMumentFragment.kt
>          lockerViewModel.myMuments.launchWhenCreated(viewLifecycleOwner.lifecycleScope){
해당 이유는 궁금하시다면 나중에 다시 물어봐주세요 :)

2023-01-27 13:03 UTC, KkamSonLee requested changes
리뷰완!!

2023-01-27 13:03 UTC, KkamSonLee commented on core_dependent/src/main/java/com/mument_android/core_dependent/ext/LifecycleCoroutineScopeExtensions.kt
> +    flow: LifecycleCoroutineScope, crossinline block: suspend (T) -> Unit
요거는 왜 수정하셨나요!?

2023-01-29 05:17 UTC, lhb8106 commented on core_dependent/src/main/java/com/mument_android/core_dependent/ext/LifecycleCoroutineScopeExtensions.kt
> +    flow: LifecycleCoroutineScope, crossinline block: suspend (T) -> Unit
오 잘못 뭐 바꾸다가 바뀐 거 같네여 ! 지금 하던거만 어떻게 해보고... 수정해서 피알날릴게엽!

2023-01-29 05:18 UTC, SONPYEONGHWA approved these changes
고생하셨습니다~~!!!

2023-01-29 05:18 UTC, SONPYEONGHWA commented on app/src/main/java/com/mument_android/app/di/NetworkModule.kt
> +                )
ㅋㅋㅋㅋㅋㅋㅋㅋ시크 민호 ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

2023-01-29 05:18 UTC, SONPYEONGHWA commented on feature/locker/src/main/java/com/mument_android/locker/LockerFragment.kt
> +    }
나중에 navigator 모듈 활용해서 구현하면 통일성이 있겠네욥!!

2023-01-29 07:50 UTC, KkamSonLee commented on app/src/main/java/com/mument_android/app/di/NetworkModule.kt
> +                )
메모처럼 기억하자구 쓴거라 너무 시크하게 쓴거같네요 ㅋ쿠ㅜㅜ

2023-01-29 07:50 UTC, KkamSonLee approved these changes

2023-01-29 08:36 UTC, merged