Hotfix/release fix
team-MUMENT/MUMENT-AOS pull request #261
Opened 2023-03-13 15:37 UTC by KkamSonLee

## 🎸 작업한 내용
- 로그인 되게 바꾸기
- 안 되면 나도 몰루... 키해시가 자주 바뀌네..?

2023-03-13 16:16 UTC, lhb8106 approved these changes
제발 됐음 좋겠다,,, 늦은 시간까지 고생하셨어용.........!

2023-03-13 22:21 UTC, SONPYEONGHWA requested changes

2023-03-13 22:21 UTC, SONPYEONGHWA commented on app/build.gradle.kts
> +            keyPassword = "alsgh478"
이거는 앱서명 정보들인데 깃에 안올리는게 좋지 않을까??

2023-03-14 05:33 UTC, KkamSonLee commented on app/build.gradle.kts
> +            keyPassword = "alsgh478"
형꺼로 고쳐둘게요~!!!

2023-03-14 11:06 UTC, merged